=== fool-byte/fool-byte.github.io/filmoteka.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://marekbostik.cz/filmoteka"
           xmlns:ft="http://marekbostik.cz/filmoteka"
           elementFormDefault="qualified"
           xmlns:sch="http://purl.oclc.org/dsdl/schematron">

    <xs:simpleType name="nonEmptyString">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="imdbIdType">
        <xs:restriction base="xs:string">
            <xs:pattern value="tt\d{7,8}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="rokType">
        <xs:restriction base="xs:gYear">
            <xs:minInclusive value="1900"/>
            <xs:maxInclusive value="2030"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="roleType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="reziser"/>
            <xs:enumeration value="scenarista"/>
            <xs:enumeration value="kameraman"/>
            <xs:enumeration value="skladatel"/>
            <xs:enumeration value="showrunner"/>
            <xs:enumeration value="herec"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="typStopyType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="original"/>
            <xs:enumeration value="dabing"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="nazvyType">
        <xs:sequence>
            <xs:element name="cesky" type="ft:nonEmptyString"/>
            <xs:element name="originalni" type="ft:nonEmptyString"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="osobaType">
        <xs:sequence>
            <xs:element name="jmeno" type="ft:nonEmptyString"/>
            <xs:element name="prijmeni" type="ft:nonEmptyString"/>
        </xs:sequence>
        <xs:attribute name="role" type="ft:roleType" use="required"/>
        <xs:attribute name="postava" type="xs:string" use="optional"/>
    </xs:complexType>

    <xs:complexType name="osobyType">
        <xs:sequence>
            <xs:element name="osoba" type="ft:osobaType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="zanryType">
        <xs:sequence>
            <xs:element name="zanr" type="ft:nonEmptyString" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="lokalizaceStopaType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="typ" type="ft:typStopyType" use="required"/>
                <xs:attribute name="jazyk" type="xs:language" use="required"/>
                <xs:attribute name="kanaly" type="xs:string"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="lokalizaceTitulkyType">
        <xs:sequence>
            <xs:element name="titulek" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:simpleContent>
                        <xs:extension base="xs:string">
                            <xs:attribute name="jazyk" type="xs:language" use="required"/>
                        </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="lokalizaceType">
        <xs:sequence>
            <xs:element name="stopa" type="ft:lokalizaceStopaType" maxOccurs="unbounded"/>
            <xs:element name="titulky" type="ft:lokalizaceTitulkyType" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="formatType">
        <xs:sequence>
            <xs:element name="nosic" type="ft:nonEmptyString"/>
            <xs:element name="edice" type="xs:string"/>
            <xs:element name="region" type="xs:string"/>
            <xs:element name="zvuk" type="xs:string" maxOccurs="unbounded"/>
            <xs:element name="video" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="hodnoceniType">
        <xs:sequence>
            <xs:element name="osobni">
                <xs:simpleType>
                    <xs:restriction base="xs:decimal">
                        <xs:minInclusive value="0"/>
                        <xs:maxInclusive value="10"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="imdb">
                <xs:simpleType>
                    <xs:restriction base="xs:decimal">
                        <xs:minInclusive value="0"/>
                        <xs:maxInclusive value="10"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="csfd" type="xs:integer" minOccurs="0"/>
            <xs:element name="rottenTomatoes" type="xs:integer" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="multimediaType">
        <xs:sequence>
            <xs:element name="obrazek" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:simpleContent>
                         <xs:extension base="xs:anyURI">
                            <xs:attribute name="typ" type="xs:string" use="required"/>
                         </xs:extension>
                    </xs:simpleContent>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="infoSerialType">
        <xs:sequence>
             <xs:element name="pocetSerii" type="xs:positiveInteger"/>
             <xs:element name="pocetEpizod" type="xs:positiveInteger"/>
        </xs:sequence>
    </xs:complexType>

    <xs:group name="headerGroup">
        <xs:sequence>
            <xs:element name="nazvy" type="ft:nazvyType"/>
            <xs:element name="rok" type="ft:rokType"/>
        </xs:sequence>
    </xs:group>

    <xs:group name="obsahGroup">
        <xs:sequence>
            <xs:element name="osoby" type="ft:osobyType"/>
            <xs:element name="zanry" type="ft:zanryType"/>
        </xs:sequence>
    </xs:group>

    <xs:group name="footerGroup">
        <xs:sequence>
            <xs:element name="lokalizace" type="ft:lokalizaceType"/>
            <xs:element name="format" type="ft:formatType"/>
            <xs:element name="hodnoceni" type="ft:hodnoceniType"/>
            <xs:element name="anotace" type="xs:string"/>
            <xs:element name="poznamka" type="xs:string" minOccurs="0"/>
            <xs:element name="multimedia" type="ft:multimediaType"/>
            <xs:element name="pridano" type="xs:date"/>
        </xs:sequence>
    </xs:group>

    <xs:complexType name="filmType">
        <xs:sequence>
            <xs:group ref="ft:headerGroup"/>
            
            <xs:element name="delka" type="xs:positiveInteger"/>
            <xs:element name="vekoveOmezeni" type="xs:positiveInteger"/> <xs:group ref="ft:obsahGroup"/>
            <xs:group ref="ft:footerGroup"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="imdbId" type="ft:imdbIdType"/>
    </xs:complexType>

    <xs:complexType name="serialType">
        <xs:sequence>
            <xs:group ref="ft:headerGroup"/>
            
            <xs:element name="rokKonec" type="ft:rokType" minOccurs="0"/>
            <xs:element name="delka" type="xs:positiveInteger"/>
            <xs:element name="infoSerial" type="ft:infoSerialType"/>
            
            <xs:group ref="ft:obsahGroup"/>
            
            <xs:element name="vekoveOmezeni" type="xs:positiveInteger"/> <xs:group ref="ft:footerGroup"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
        <xs:attribute name="imdbId" type="ft:imdbIdType"/>
    </xs:complexType>

    <xs:element name="filmoteka">
        <xs:complexType>
            <xs:choice minOccurs="0" maxOccurs="unbounded">
                <xs:element name="film" type="ft:filmType"/>
                <xs:element name="serial" type="ft:serialType"/>
            </xs:choice>
            <xs:attribute name="majitel" type="ft:nonEmptyString" use="required"/>
            <xs:attribute name="vytvoreno" type="xs:date" use="required"/>
        </xs:complexType>

        <xs:key name="uniqueId">
            <xs:selector xpath="ft:film | ft:serial"/>
            <xs:field xpath="@id"/>
        </xs:key>
        <xs:key name="uniqueImdbId">
            <xs:selector xpath="ft:film | ft:serial"/>
            <xs:field xpath="@imdbId"/>
        </xs:key>
    </xs:element>

    <xs:annotation>
        <xs:appinfo>
            <sch:schema xmlns:sch="http://purl.oclc.org/dsdl/schematron">
                <sch:pattern>
                    <sch:rule context="ft:film | ft:serial">
                        <sch:assert test="ft:pridano &lt;= current-date()">Datum přidání nesmí být v budoucnosti</sch:assert>
                    </sch:rule>
                    <sch:rule context="ft:serial">
                        <sch:assert test="not(ft:rokKonec) or (ft:rokKonec >= ft:rok)">Rok konce seriálu musí být stejný nebo vyšší než rok začátku.</sch:assert>
                    </sch:rule>
                </sch:pattern>
            </sch:schema>
        </xs:appinfo>
    </xs:annotation>
</xs:schema>

=== fool-byte/fool-byte.github.io/filmoteka.xml
<?xml version="1.0" encoding="UTF-8"?>
<filmoteka xmlns="http://marekbostik.cz/filmoteka"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://marekbostik.cz/filmoteka filmoteka.xsd"
           majitel="Marek Boštík"
           vytvoreno="2024-11-26">

    <film id="f001" imdbId="tt2906216">
        <nazvy>
            <cesky>Dungeons and Dragons: Čest zlodějů</cesky>
            <originalni>Dungeons &amp; Dragons: Honor Among Thieves</originalni>
        </nazvy>

        <rok>2023</rok>
        <delka>134</delka>
        <vekoveOmezeni>12</vekoveOmezeni>

        <osoby>
            <osoba role="reziser">
                <jmeno>Jonathan</jmeno>
                <prijmeni>Goldstein</prijmeni>
            </osoba>
            <osoba role="reziser">
                <jmeno>John Francis</jmeno>
                <prijmeni>Daley</prijmeni>
            </osoba>
            <osoba role="scenarista">
                <jmeno>Michael</jmeno>
                <prijmeni>Gilio</prijmeni>
            </osoba>
            <osoba role="herec" postava="Edgin Darvis">
                <jmeno>Chris</jmeno>
                <prijmeni>Pine</prijmeni>
            </osoba>
            <osoba role="herec" postava="Holga Kilgore">
                <jmeno>Michelle</jmeno>
                <prijmeni>Rodriguez</prijmeni>
            </osoba>
            <osoba role="herec" postava="Simon Aumar">
                <jmeno>Justice</jmeno>
                <prijmeni>Smith</prijmeni>
            </osoba>
            <osoba role="herec" postava="Xenk Yendar">
                <jmeno>Regé-Jean</jmeno>
                <prijmeni>Page</prijmeni>
            </osoba>
            <osoba role="herec" postava="Forge Fitzwilliam">
                <jmeno>Hugh</jmeno>
                <prijmeni>Grant</prijmeni>
            </osoba>
             <osoba role="herec" postava="Sofina">
                <jmeno>Daisy</jmeno>
                <prijmeni>Head</prijmeni>
            </osoba>
        </osoby>

        <zanry>
            <zanr>Fantasy</zanr>
            <zanr>Dobrodružný</zanr>
            <zanr>Komedie</zanr>
        </zanry>

        <lokalizace>
            <stopa typ="original" jazyk="en" kanaly="7.1">angličtina</stopa>
            <stopa typ="dabing" jazyk="cs" kanaly="5.1">čeština</stopa>
            <titulky>
                <titulek jazyk="cs">čeština</titulek>
                <titulek jazyk="en">angličtina</titulek>
            </titulky>
        </lokalizace>

        <format>
            <nosic>4K UHD Blu-ray</nosic>
            <edice>SteelBook</edice>
            <region>B</region>
            <zvuk>Dolby Atmos</zvuk>
            <video>HDR10+</video>
        </format>

        <hodnoceni>
            <osobni>8</osobni>
            <imdb>7.3</imdb>
            <csfd>76</csfd>
            <rottenTomatoes>91</rottenTomatoes>
        </hodnoceni>

        <anotace>Skupina nepravděpodobných dobrodruhů se vydává na epickou výpravu, aby získala ztracenou relikvii.</anotace>
        <poznamka>SteelBook s 3D lentikulárním magnetem.</poznamka>

        <multimedia>
            <obrazek typ="obal_predni">img/f001_front.jpg</obrazek>
            <obrazek typ="obal_zadni">img/f001_back.jpg</obrazek>
        </multimedia>

        <pridano>2023-08-10</pridano>
    </film>

    <film id="f002" imdbId="tt15398776">
        <nazvy>
            <cesky>Oppenheimer</cesky>
            <originalni>Oppenheimer</originalni>
        </nazvy>
        <rok>2023</rok>
        <delka>180</delka>
        <vekoveOmezeni>15</vekoveOmezeni>

        <osoby>
            <osoba role="reziser">
                <jmeno>Christopher</jmeno><prijmeni>Nolan</prijmeni>
            </osoba>
            <osoba role="scenarista">
                <jmeno>Christopher</jmeno><prijmeni>Nolan</prijmeni>
            </osoba>
            <osoba role="kameraman">
                <jmeno>Hoyte</jmeno><prijmeni>van Hoytema</prijmeni>
            </osoba>
            <osoba role="herec" postava="J. Robert Oppenheimer">
                <jmeno>Cillian</jmeno><prijmeni>Murphy</prijmeni>
            </osoba>
            <osoba role="herec" postava="Kitty Oppenheimer">
                <jmeno>Emily</jmeno><prijmeni>Blunt</prijmeni>
            </osoba>
            <osoba role="herec" postava="Lewis Strauss">
                <jmeno>Robert</jmeno><prijmeni>Downey Jr.</prijmeni>
            </osoba>
        </osoby>

        <zanry>
            <zanr>Životopisný</zanr>
            <zanr>Drama</zanr>
            <zanr>Historický</zanr>
        </zanry>

        <lokalizace>
            <stopa typ="original" jazyk="en" kanaly="5.1">angličtina</stopa>
            <titulky>
                <titulek jazyk="cs">čeština</titulek>
            </titulky>
        </lokalizace>

        <format>
            <nosic>4K UHD Blu-ray</nosic>
            <edice>SteelBook</edice>
            <region>free</region>
            <zvuk>Dolby Atmos</zvuk>
            <video>Dolby Vision</video>
            <video>HDR10</video>
        </format>

        <hodnoceni>
            <osobni>10</osobni>
            <imdb>8.3</imdb>
            <csfd>88</csfd>
        </hodnoceni>

        <anotace>Příběh otce atomové bomby J. Roberta Oppenheimera.</anotace>
        <multimedia>
            <obrazek typ="obal_predni">img/f002_front.jpg</obrazek>
        </multimedia>
        <pridano>2024-02-28</pridano>
    </film>

    <film id="f003" imdbId="tt0816692">
        <nazvy>
            <cesky>Interstellar</cesky>
            <originalni>Interstellar</originalni>
        </nazvy>
        <rok>2014</rok>
        <delka>169</delka>
        <vekoveOmezeni>12</vekoveOmezeni>

        <osoby>
            <osoba role="reziser">
                <jmeno>Christopher</jmeno><prijmeni>Nolan</prijmeni>
            </osoba>
            <osoba role="scenarista">
                <jmeno>Jonathan</jmeno><prijmeni>Nolan</prijmeni>
            </osoba>
            <osoba role="skladatel">
                <jmeno>Hans</jmeno><prijmeni>Zimmer</prijmeni>
            </osoba>
            <osoba role="herec" postava="Cooper">
                <jmeno>Matthew</jmeno><prijmeni>McConaughey</prijmeni>
            </osoba>
            <osoba role="herec" postava="Brand">
                <jmeno>Anne</jmeno><prijmeni>Hathaway</prijmeni>
            </osoba>
             <osoba role="herec" postava="Murph">
                <jmeno>Jessica</jmeno><prijmeni>Chastain</prijmeni>
            </osoba>
        </osoby>

        <zanry>
            <zanr>Sci-Fi</zanr>
            <zanr>Dobrodružný</zanr>
            <zanr>Drama</zanr>
        </zanry>

        <lokalizace>
            <stopa typ="original" jazyk="en" kanaly="5.1">angličtina</stopa>
            <stopa typ="dabing" jazyk="cs" kanaly="5.1">čeština</stopa>
            <titulky>
                <titulek jazyk="cs">čeština</titulek>
                <titulek jazyk="en">angličtina</titulek>
            </titulky>
        </lokalizace>

        <format>
            <nosic>Blu-ray</nosic>
            <edice>Standard</edice>
            <region>B</region>
            <zvuk>DTS-HD Master Audio</zvuk>
            <zvuk>Dolby Digital 5.1</zvuk>
        </format>

        <hodnoceni>
            <osobni>10</osobni>
            <imdb>8.7</imdb>
            <csfd>84</csfd>
            <rottenTomatoes>73</rottenTomatoes>
        </hodnoceni>

        <anotace>Tým průzkumníků cestuje červí dírou ve vesmíru, aby zajistil přežití lidstva.</anotace>
        <multimedia>
            <obrazek typ="obal_predni">img/f003_front.jpg</obrazek>
        </multimedia>
        <pridano>2015-05-15</pridano>
    </film>

    <serial id="s001" imdbId="tt0944947">
        <nazvy>
            <cesky>Hra o trůny</cesky>
            <originalni>Game of Thrones</originalni>
        </nazvy>

        <rok>2011</rok>
        <rokKonec>2019</rokKonec>
        <delka>60</delka>

        <infoSerial>
            <pocetSerii>8</pocetSerii>
            <pocetEpizod>73</pocetEpizod>
        </infoSerial>

        <osoby>
            <osoba role="showrunner">
                <jmeno>David</jmeno><prijmeni>Benioff</prijmeni>
            </osoba>
            <osoba role="showrunner">
                <jmeno>D. B.</jmeno><prijmeni>Weiss</prijmeni>
            </osoba>
            <osoba role="herec" postava="Daenerys Targaryen">
                <jmeno>Emilia</jmeno><prijmeni>Clarke</prijmeni>
            </osoba>
            <osoba role="herec" postava="Jon Snow">
                <jmeno>Kit</jmeno><prijmeni>Harington</prijmeni>
            </osoba>
            <osoba role="herec" postava="Tyrion Lannister">
                <jmeno>Peter</jmeno><prijmeni>Dinklage</prijmeni>
            </osoba>
             <osoba role="herec" postava="Cersei Lannister">
                <jmeno>Lena</jmeno><prijmeni>Headey</prijmeni>
            </osoba>
        </osoby>

        <zanry>
            <zanr>Fantasy</zanr>
            <zanr>Drama</zanr>
            <zanr>Dobrodružný</zanr>
        </zanry>
        <vekoveOmezeni>18</vekoveOmezeni>

        <lokalizace>
            <stopa typ="original" jazyk="en" kanaly="5.1">angličtina</stopa>
            <titulky>
                <titulek jazyk="cs">čeština</titulek>
                <titulek jazyk="en">angličtina</titulek>
            </titulky>
        </lokalizace>

        <format>
            <nosic>Blu-ray</nosic>
            <edice>Kompletní série</edice>
            <region>B</region>
            <zvuk>Dolby Atmos</zvuk>
        </format>

        <hodnoceni>
            <osobni>9</osobni>
            <imdb>9.2</imdb>
            <csfd>91</csfd>
            <rottenTomatoes>89</rottenTomatoes>
